import os

PROMETHEUS_URL = os.getenv("PROMETHEUS_URL", "http://localhost:9090")
TARGET_NAMESPACE = os.getenv("TARGET_NAMESPACE", "default")
TARGET_DEPLOYMENT = os.getenv("TARGET_DEPLOYMENT", "task-manager")

ZSCORE_WINDOW_SIZE = 20
ZSCORE_THRESHOLD = 2.5

IF_CONTAMINATION = 0.05
IF_N_ESTIMATORS = 100

RF_N_ESTIMATORS = 100
RF_CONFIDENCE_MIN = 0.70

POLL_INTERVAL_SECONDS = 30
COOLDOWN_SECONDS = 180
MAX_REPLICAS = 5

ACTION_SCALE_UP = "SCALE_UP"
ACTION_DELETE_RECREATE = "DELETE_AND_RECREATE"
ACTION_ROLLING_RESTART = "ROLLING_RESTART"
ACTION_NO_ACTION = "NO_ACTION"

IF_MODEL_PATH = "models/isolation_forest.pkl"
RF_MODEL_PATH = "models/random_forest.pkl"
FEEDBACK_LOG_PATH = "logs/healing_actions.csv"
